// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	Event(ctx context.Context, in *Event, opts ...grpc.CallOption) (*emptypb.Empty, error)
	BatchEvents(ctx context.Context, in *EventBatch, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_StreamEventsClient, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) Event(ctx context.Context, in *Event, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/telemetry.TelemetryService/event", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) BatchEvents(ctx context.Context, in *EventBatch, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/telemetry.TelemetryService/batchEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (TelemetryService_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TelemetryService_ServiceDesc.Streams[0], "/telemetry.TelemetryService/streamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &telemetryServiceStreamEventsClient{stream}
	return x, nil
}

type TelemetryService_StreamEventsClient interface {
	Send(*Event) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type telemetryServiceStreamEventsClient struct {
	grpc.ClientStream
}

func (x *telemetryServiceStreamEventsClient) Send(m *Event) error {
	return x.ClientStream.SendMsg(m)
}

func (x *telemetryServiceStreamEventsClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility
type TelemetryServiceServer interface {
	Event(context.Context, *Event) (*emptypb.Empty, error)
	BatchEvents(context.Context, *EventBatch) (*emptypb.Empty, error)
	StreamEvents(TelemetryService_StreamEventsServer) error
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTelemetryServiceServer struct {
}

func (UnimplementedTelemetryServiceServer) Event(context.Context, *Event) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Event not implemented")
}
func (UnimplementedTelemetryServiceServer) BatchEvents(context.Context, *EventBatch) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchEvents not implemented")
}
func (UnimplementedTelemetryServiceServer) StreamEvents(TelemetryService_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_Event_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).Event(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telemetry.TelemetryService/event",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).Event(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_BatchEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).BatchEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/telemetry.TelemetryService/batchEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).BatchEvents(ctx, req.(*EventBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryServiceServer).StreamEvents(&telemetryServiceStreamEventsServer{stream})
}

type TelemetryService_StreamEventsServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*Event, error)
	grpc.ServerStream
}

type telemetryServiceStreamEventsServer struct {
	grpc.ServerStream
}

func (x *telemetryServiceStreamEventsServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *telemetryServiceStreamEventsServer) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "event",
			Handler:    _TelemetryService_Event_Handler,
		},
		{
			MethodName: "batchEvents",
			Handler:    _TelemetryService_BatchEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamEvents",
			Handler:       _TelemetryService_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "telemetry.proto",
}
