package db

import (
	"database/sql"
	"fmt"

	"github.com/Jefschlarski/ps-intelbras-iot/telemetry_consumer/src/config"
	_ "github.com/lib/pq"
)

// ConnectDB conecta ao banco
func ConnectDB(dbConfig *config.DBConfig) (*sql.DB, error) {
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s "+
		"password=%s dbname=%s sslmode=disable",
		dbConfig.Host, dbConfig.Port, dbConfig.User, dbConfig.Pass, dbConfig.Database)
	db, err := sql.Open("postgres", psqlInfo)
	if err != nil {
		panic(err)
	}

	err = db.Ping()
	if err != nil {
		panic(err)
	}

	fmt.Println("Connected to " + dbConfig.Database)

	_, err = db.Exec(`CREATE TABLE IF NOT EXISTS "telemetry" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" int NOT NULL,
  "event_type" int NOT NULL,
  "event_time" timestamp NOT NULL,
  "value_int" int,
  "value_float" float,
  "value_string" varchar
);`)

	if err != nil {
		panic(err)
	}

	return db, nil
}
